apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
  #namespace: mulhome-mysql
spec:
  storageClassName: nfs-client
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
